server:
  port: ${SERVER_PORT:8080}

spring:
<<<<<<< HEAD
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/parking_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:your_password}
    driver-class-name: org.postgresql.Driver
=======

>>>>>>> 8fdfb93 (feat: connect supabase and update configuration)
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

jwt:
  issuer: ${JWT_ISSUER:ParkingBuilding.CoreApi}
  audience: ${JWT_AUDIENCE:ParkingBuilding.Frontend}
  secret: ${JWT_SECRET:DEVELOPMENT_SECRET_KEY_FOR_LOCAL_TESTING_ONLY_2026_SWP391}
