import React, { useState, useEffect } from "react";
import QRCode from "qrcode";
import { CheckCircle2, Copy, AlertCircle, Loader2, CopyCheck, Clock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { reservationService } from "../../../services/reservationService";

const parseEMVCo = (str) => {
  if (!str) return {};
  let i = 0;
  const tags = {};
  while (i < str.length) {
    const id = str.substring(i, i + 2);
    const len = parseInt(str.substring(i + 2, i + 4), 10);
    if (isNaN(len)) break;
    const val = str.substring(i + 4, i + 4 + len);
    tags[id] = val;
    i += 4 + len;
  }
  return tags;
};

const extractAccountNumberFromVietQR = (qrCodeStr) => {
  try {
    const tags = parseEMVCo(qrCodeStr);
    const tag38 = tags['38'];
    if (tag38) {
      const subTags = parseEMVCo(tag38);
      const subTag01 = subTags['01'];
      if (subTag01) {
        const subSubTags = parseEMVCo(subTag01);
        return subSubTags['01'];
      }
    }
  } catch (e) {
    console.error("Failed to parse VietQR", e);
  }
  return null;
};

export default function PaymentStep({ activeReservation, onPaymentComplete, onCancel, onExpire }) {
  const [isPaid, setIsPaid] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [copiedField, setCopiedField] = useState(""); // Track which field was copied: 'account', 'amount', 'content'
  const [timeLeft, setTimeLeft] = useState(activeReservation?.remainingSeconds || 600); // 10 minutes default
  const [qrDataUrl, setQrDataUrl] = useState("");
  const [qrError, setQrError] = useState("");

  const amount = activeReservation?.bookingAmount || 10000;
  
  // Custom Merchant Details matching PayOS Sandbox/MB
  const bankName = "Ngân hàng TMCP Quân đội";
  const bankShortName = "MB Bank";
  const accountName = "NGUYEN HOANG HUNG";

  const qrPayload = activeReservation?.qrCode || activeReservation?.checkoutUrl || "";
  const extractedAccount = extractAccountNumberFromVietQR(activeReservation?.qrCode);
  const accountNumber = extractedAccount || "VQRQAKCTL6498";

  // Match the description generated by PayOSPaymentService ( $"RES {reservation.Id}" )
  const transferContent = activeReservation?.id ? `RES ${activeReservation.id}` : (activeReservation?.reservationCode || `RES-${new Date().toISOString().split('T')[0].replace(/-/g, '')}-${Math.floor(Math.random() * 1000000)}`);

  useEffect(() => {
    let cancelled = false;

    const renderQr = async () => {
      setQrError("");

      if (!qrPayload) {
        setQrDataUrl("");
        setQrError("Khong co du lieu QR tu PayOS.");
        return;
      }

      try {
        const dataUrl = await QRCode.toDataURL(qrPayload, {
          width: 220,
          margin: 1,
          errorCorrectionLevel: "M",
          color: {
            dark: "#0f172a",
            light: "#ffffff"
          }
        });

        if (!cancelled) {
          setQrDataUrl(dataUrl);
        }
      } catch (error) {
        console.error("Unable to render PayOS QR:", error);
        if (!cancelled) {
          setQrDataUrl("");
          setQrError("Khong the tao anh QR.");
        }
      }
    };

    renderQr();

    return () => {
      cancelled = true;
    };
  }, [qrPayload]);

  // Copy helper
  const handleCopy = (text, fieldName) => {
    navigator.clipboard.writeText(text);
    setCopiedField(fieldName);
    setTimeout(() => setCopiedField(""), 2000);
  };

  // 1. Countdown Timer
  useEffect(() => {
    if (timeLeft <= 0) {
      // Auto-cancel and go back to step 1 when time runs out
      const autoCancel = async () => {
        try {
          if (onExpire) {
            await onExpire();
          } else {
            await onCancel();
          }
        } catch (e) {
          console.error("Auto cancel failed:", e);
        }
      };
      autoCancel();
      return;
    }

    const timerId = setInterval(() => {
      setTimeLeft(prev => prev - 1);
    }, 1000);

    return () => clearInterval(timerId);
  }, [timeLeft, onCancel, onExpire]);

  // Format timeLeft as MM:SS
  const formatTime = (seconds) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  };

  // 2. Auto Polling payment status every 3 seconds
  useEffect(() => {
    if (!activeReservation || isPaid) return;

    const intervalId = setInterval(async () => {
      try {
        const latest = await reservationService.payReservation(activeReservation.id).catch(() => null);
        if (latest && (latest.status === "CONFIRMED" || latest.paymentStatus === "PAID")) {
          clearInterval(intervalId);
          setIsPaid(true);
          setTimeout(() => {
            onPaymentComplete();
          }, 1500);
        }
      } catch (e) {
        console.error("Lỗi tự động kiểm tra thanh toán:", e);
      }
    }, 3000);

    return () => clearInterval(intervalId);
  }, [activeReservation, isPaid, onPaymentComplete]);

  // 3. Manual verification button
  const handleCheckPaymentStatus = async () => {
    setErrorMessage("");
    try {
      if (activeReservation) {
        await reservationService.payReservation(activeReservation.id);
        setIsPaid(true);
        setTimeout(() => {
          onPaymentComplete();
        }, 1500);
      }
    } catch (e) {
      setErrorMessage(e.message || "Giao dịch chưa được thanh toán trên PayOS. Vui lòng thanh toán trước.");
    }
  };

  if (isPaid) {
    return (
      <div className="text-center py-12 animate-in fade-in zoom-in duration-500">
        <div className="w-20 h-20 bg-emerald-50 text-emerald-500 rounded-full flex items-center justify-center mx-auto mb-6 border border-emerald-100 shadow-inner">
          <CheckCircle2 className="w-10 h-10 animate-bounce" />
        </div>
        <h3 className="text-2xl font-black text-slate-800 mb-2">Thanh toán thành công!</h3>
        <p className="text-slate-500 max-w-md mx-auto text-sm">
          Hệ thống đã ghi nhận giao dịch thanh toán từ PayOS. Đang khởi tạo thẻ check-in...
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500 max-w-3xl mx-auto py-2">
      
      {/* ⚠️ Countdown Timer Alert */}
      <div className="bg-amber-50 border border-amber-200 text-amber-800 px-4 py-3 rounded-2xl flex items-center justify-between text-sm shadow-sm">
        <div className="flex items-center gap-2 font-bold">
          <Clock className="w-4 h-4 text-amber-600 animate-pulse" />
          <span>Thời gian giữ chỗ và thanh toán còn lại:</span>
        </div>
        <span className="font-mono text-lg font-black bg-white px-3 py-1 rounded-xl border border-amber-300 text-amber-700 shadow-sm animate-pulse">
          {formatTime(timeLeft)}
        </span>
      </div>

      <div className="bg-white rounded-3xl border border-slate-200 p-6 md:p-8 shadow-sm">
        {/* Header Instruction */}
        <div className="flex items-start gap-3 bg-slate-50 border border-slate-100 p-4 rounded-2xl mb-6">
          <div className="bg-amber-100 p-2 rounded-xl text-amber-600">
            <span className="text-lg">💡</span>
          </div>
          <p className="text-sm font-semibold text-slate-700 leading-relaxed">
            Mở App Ngân hàng bất kỳ để <strong className="text-indigo-600">quét mã VietQR</strong> hoặc <strong className="text-slate-800">chuyển khoản</strong> chính xác số tiền bên dưới.
          </p>
        </div>

        {/* Two-Column QR Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center border-b border-slate-150 pb-6 mb-6">
          {/* Left: VietQR Code Box */}
          <div className="flex flex-col items-center justify-center bg-slate-50 border border-slate-200/60 rounded-3xl p-6 text-center">
            {/* VietQR Pro Header */}
            <div className="flex items-center gap-1.5 mb-4">
              <span className="text-lg font-black tracking-tighter text-red-600">Viet</span>
              <span className="text-lg font-black tracking-tighter text-blue-600">QR</span>
              <span className="bg-emerald-500 text-white text-[10px] font-black px-1.5 py-0.5 rounded-md uppercase tracking-widest ml-1 shadow-sm">
                Pro
              </span>
            </div>

            <div className="bg-white p-4 rounded-2xl shadow-sm border border-slate-100">
              {qrDataUrl ? (
                <div className="flex flex-col items-center">
                  <img 
                    src={qrDataUrl} 
                    alt="PayOS VietQR Code" 
                    className="w-48 h-48 object-contain mx-auto"
                  />
                  {activeReservation?.checkoutUrl && (
                    <a 
                      href={activeReservation.checkoutUrl} 
                      target="_blank" 
                      rel="noreferrer"
                      className="mt-3 text-xs text-indigo-600 hover:text-indigo-800 font-bold underline"
                    >
                      Hoặc mở trang thanh toán PayOS
                    </a>
                  )}
                </div>
              ) : qrError ? (
                <div className="w-48 h-48 flex items-center justify-center text-rose-500 text-xs text-center px-4">
                  {qrError}
                </div>
              ) : (
                <div className="w-48 h-48 flex items-center justify-center text-slate-400 text-xs">
                  Đang khởi tạo QR...
                </div>
              )}
            </div>

            {/* Napas 247 | Bank Badges */}
            <div className="flex items-center gap-3 mt-4 text-xs font-bold text-slate-400 border-t border-slate-200/60 pt-3 w-full justify-center">
              <span className="text-indigo-600 italic">napas 247</span>
              <span className="text-slate-300">|</span>
              <span className="text-blue-700 font-extrabold tracking-wider">MB</span>
            </div>
          </div>

          {/* Right: Bank Details Info */}
          <div className="space-y-4">
            {/* Bank Entity */}
            <div className="flex items-center gap-3 border-b border-slate-100 pb-3">
              <div className="w-10 h-10 bg-indigo-50 rounded-full flex items-center justify-center text-indigo-600 border border-indigo-100">
                <span className="font-extrabold text-sm text-indigo-700">MB</span>
              </div>
              <div>
                <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">Ngân hàng</p>
                <p className="font-black text-slate-800 text-sm leading-tight">{bankName}</p>
              </div>
            </div>

            {/* Owner Name */}
            <div>
              <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-0.5">Chủ tài khoản</p>
              <p className="font-bold text-slate-800 text-base">{accountName}</p>
            </div>

            {/* Account Number */}
            <div>
              <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-0.5">Số tài khoản</p>
              <div className="flex items-center justify-between bg-slate-50 px-3.5 py-2 rounded-xl border border-slate-200">
                <span className="font-mono font-black text-slate-800">{accountNumber}</span>
                <button 
                  onClick={() => handleCopy(accountNumber, "account")}
                  className="text-xs font-bold text-indigo-600 hover:text-indigo-800 flex items-center gap-1 transition-colors"
                >
                  {copiedField === "account" ? (
                    <>
                      <CopyCheck className="w-3.5 h-3.5 text-emerald-600" />
                      <span className="text-emerald-600 text-[10px]">Đã sao chép</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Sao chép</span>
                    </>
                  )}
                </button>
              </div>
            </div>

            {/* Amount */}
            <div>
              <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-0.5">Số tiền</p>
              <div className="flex items-center justify-between bg-slate-50 px-3.5 py-2 rounded-xl border border-slate-200">
                <span className="font-black text-rose-600 text-base">{amount.toLocaleString("vi-VN")} VND</span>
                <button 
                  onClick={() => handleCopy(amount.toString(), "amount")}
                  className="text-xs font-bold text-indigo-600 hover:text-indigo-800 flex items-center gap-1 transition-colors"
                >
                  {copiedField === "amount" ? (
                    <>
                      <CopyCheck className="w-3.5 h-3.5 text-emerald-600" />
                      <span className="text-emerald-600 text-[10px]">Đã sao chép</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Sao chép</span>
                    </>
                  )}
                </button>
              </div>
            </div>

            {/* Content / Memo */}
            <div>
              <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-0.5">Nội dung</p>
              <div className="flex items-center justify-between bg-slate-50 px-3.5 py-2 rounded-xl border border-slate-200">
                <span className="font-mono font-black text-slate-800">{transferContent}</span>
                <button 
                  onClick={() => handleCopy(transferContent, "content")}
                  className="text-xs font-bold text-indigo-600 hover:text-indigo-800 flex items-center gap-1 transition-colors"
                >
                  {copiedField === "content" ? (
                    <>
                      <CopyCheck className="w-3.5 h-3.5 text-emerald-600" />
                      <span className="text-emerald-600 text-[10px]">Đã sao chép</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Sao chép</span>
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom Warning & Actions */}
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mt-6">
          <div className="text-xs font-medium text-slate-500 leading-normal">
            ⚠️ <span className="font-bold text-rose-600">Lưu ý:</span> Nhập chính xác số tiền <strong className="text-slate-800">{amount.toLocaleString("vi-VN")} VND</strong> và nội dung <strong className="text-slate-800">{transferContent}</strong> khi chuyển khoản để giao dịch được xử lý tự động ngay lập tức.
          </div>
        </div>
      </div>

      {errorMessage && (
        <div className="bg-rose-50 border border-rose-200 text-rose-800 p-4 rounded-2xl flex items-start gap-2.5 text-xs animate-in fade-in duration-300">
          <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
          <p className="font-semibold">{errorMessage}</p>
        </div>
      )}

      {/* Auto Polling Status Spinner */}
      <div className="flex items-center justify-center gap-2 text-xs text-indigo-600 font-bold bg-indigo-50 border border-indigo-100 py-3 rounded-2xl shadow-sm">
        <Loader2 className="w-4 h-4 animate-spin text-indigo-600" />
        <span>Hệ thống đang tự động kiểm tra giao dịch chuyển khoản...</span>
      </div>

      {/* Buttons */}
      <div className="flex gap-3">
        <Button 
          variant="outline"
          className="flex-1 text-slate-500 hover:text-rose-600 hover:bg-rose-50 border-slate-200 h-12 text-sm font-bold rounded-2xl"
          onClick={onCancel}
        >
          Hủy đặt chỗ
        </Button>
        <Button 
          className="flex-1 bg-emerald-600 hover:bg-emerald-700 text-white font-bold h-12 text-sm rounded-2xl shadow-md transition-all"
          onClick={handleCheckPaymentStatus}
        >
          Tôi đã thanh toán xong
        </Button>
      </div>
    </div>
  );
}
