import React, { useState } from "react";
import { CheckCircle2, QrCode, UploadCloud, Copy } from "lucide-react";
import { Button } from "@/components/ui/button";
import { reservationService } from "../../../services/reservationService";

export default function PaymentStep({ activeReservation, onPaymentComplete, onCancel }) {
  const [isPaid, setIsPaid] = useState(false);

  // In the future, this URL could come from API like `paymentInfo.qrUrl`
  // Mock image generated by QuickChart for demo purposes
  const amount = activeReservation?.bookingAmount || 15000;
  const paymentContent = `Thanh toan dat cho ${activeReservation?.reservationCode || ""}`;
  const mockQrUrl = `https://quickchart.io/qr?text=${encodeURIComponent(paymentContent)}&size=200`;

  const handleSimulatePayment = async () => {
    try {
      if (activeReservation) {
        await reservationService.payReservation(activeReservation.id);
      }
      setIsPaid(true);
      setTimeout(() => {
        onPaymentComplete();
      }, 1500);
    } catch (e) {
      alert(e.message || "Thanh toán thất bại");
    }
  };

  if (isPaid) {
    return (
      <div className="text-center py-12 animate-in fade-in zoom-in duration-500">
        <div className="w-24 h-24 bg-emerald-50 text-emerald-500 rounded-full flex items-center justify-center mx-auto mb-6">
          <CheckCircle2 className="w-12 h-12" />
        </div>
        <h3 className="text-2xl font-black text-slate-800 mb-2">Thanh toán thành công!</h3>
        <p className="text-slate-500 max-w-md mx-auto">
          Cảm ơn bạn đã hoàn tất thủ tục. Hệ thống đang chuyển hướng...
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500 max-w-md mx-auto py-4">
      <div className="text-center">
        <h3 className="text-xl font-black text-slate-800 mb-2">Thanh toán giữ chỗ</h3>
        <p className="text-sm text-slate-500">
          Vui lòng quét mã QR dưới đây bằng ứng dụng Ngân hàng hoặc MoMo để hoàn tất đặt chỗ.
        </p>
      </div>

      <div className="bg-slate-50 rounded-2xl p-6 border-2 border-dashed border-slate-200 text-center relative overflow-hidden group">

        
        <div className="bg-white p-4 rounded-xl shadow-sm inline-block border border-slate-100 mb-4 relative z-10">
          {/* TO-DO: Replace `mockQrUrl` with actual dynamic QR image from payment gateway API */}
          <img 
            src={mockQrUrl} 
            alt="Payment QR" 
            className="w-48 h-48 object-contain"
          />
        </div>
        
        <div className="space-y-3 relative z-10">
          <div className="flex justify-between items-center text-sm px-4">
            <span className="text-slate-500">Số tiền:</span>
            <span className="font-black text-indigo-600 text-lg">{amount.toLocaleString("vi-VN")}đ</span>
          </div>
          <div className="flex justify-between items-center text-sm px-4">
            <span className="text-slate-500">Nội dung CK:</span>
            <div className="flex items-center gap-2 font-semibold text-slate-700">
              {activeReservation?.reservationCode || "SWP391"}
              <Copy className="w-4 h-4 text-slate-400 cursor-pointer hover:text-indigo-600" onClick={() => alert("Đã copy nội dung")} />
            </div>
          </div>
        </div>
      </div>

      <div className="flex flex-col gap-3">
        <Button 
          className="w-full bg-emerald-600 hover:bg-emerald-700 font-bold h-12 text-lg shadow-lg shadow-emerald-200"
          onClick={handleSimulatePayment}
        >
          Tôi đã thanh toán xong
        </Button>
        <Button 
          variant="outline" 
          className="w-full text-slate-500 hover:text-rose-600 border-slate-200"
          onClick={onCancel}
        >
          Hủy đặt chỗ
        </Button>
      </div>
    </div>
  );
}
